### PR TITLE
Rewrite due to changes on CNB side

### PR DESCRIPTION
**Pull request by PHronek**

### CODE REVIEW

**Comment by boblin** [comment]
What is the purpose for this pull request?

**Comment by PHronek** [comment]
We want to use it in fantozzi, but as it is right now this gem doesnt work. CNB removed their xml exchange rates endpoint.

**Comment by boblin** [comment]
XML format seems to be working: http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.xml

**Comment by PHronek** [comment]
well yeah, now it seems to be working. But theres no documentation on CNB side that this endpoint should even exist. Or i cant find it. Also why was this gem not used in fantozzi? We thought that the xml endpoint was not working tryed to remove that ugly service which loads all that over txt file.

**Pull request closed without merging**
